const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const G=require('../docs/grading.js'),keys=JSON.parse(fs.readFileSync('docs/answer-keys.json')).keys,lessons=JSON.parse(fs.readFileSync('docs/lessons.json')).lessons;
const lesson=lessons.find(l=>l.id==='W01-AS-PL-TUE'),key=keys[`${lesson.id}:v${lesson.version}`];
function attempt(){return {lesson:{id:lesson.id,version:lesson.version},answers:Object.entries(key.answers).map(([id,e])=>({id,prompt:'Проверка',value:e.value,selectedCase:e.chooseCase?e.case:null}))};}
const grade=a=>G.evaluate(a,key,lesson.cases,lesson.words);
test('all five keys cover exact catalog IDs; all correct answers score completely',()=>{
 for(const l of lessons){const k=keys[`${l.id}:v${l.version}`];const a={lesson:{id:l.id,version:l.version},answers:Object.entries(k.answers).map(([id,e])=>({id,value:e.value,selectedCase:e.chooseCase?e.case:null}))};const r=G.evaluate(a,k,l.cases,l.words);assert.equal(r.fullyCorrect,a.answers.length);assert.deepEqual(r.incorrectIds,[]);}
});
test('case and form assessed separately; mistakes count once for retry',()=>{const a=attempt();a.answers.find(x=>x.id==='T4.3').selectedCase='Įn.';const r=grade(a);assert.equal(r.formScore.correct,50);assert.equal(r.caseScore.correct,19);assert.deepEqual(r.incorrectIds,['T4.3']);});
test('normalization accepts capitalization, surrounding whitespace, equivalent Unicode; preserves accents',()=>{assert.equal(G.normalize('  ŠEIMA  '),'šeima');assert.equal(G.normalize('s\u030c'),'š');const a=attempt();a.answers.find(x=>x.id==='T1.1').value='LANGĄ ';assert.equal(grade(a).formScore.correct,50);a.answers.find(x=>x.id==='T1.1').value='langa';const c=grade(a).checks.find(c=>c.id==='T1.1');assert.equal(c.formCorrect,false);assert.equal(c.feedback.type,'spelling');});
test('wrong stem and y/i described precisely; arbitrary errors receive factual generic explanation',()=>{const a=attempt();a.answers.find(x=>x.id==='T2.4.butas').value='darbus';a.answers.find(x=>x.id==='T1.2').value='kaiminui';a.answers.find(x=>x.id==='T3.4').value='???';const r=grade(a);assert.equal(r.checks.find(x=>x.id==='T2.4.butas').feedback.type,'different-word');assert.equal(r.checks.find(x=>x.id==='T1.2').feedback.type,'spelling');assert.equal(r.checks.find(x=>x.id==='T3.4').feedback.type,'form');assert(r.checks.every(c=>c.rule&&c.ending));});
test('empty response and empty case are errors, with full denominators',()=>{const a=attempt();const x=a.answers.find(x=>x.id==='T1.1');x.value='';x.selectedCase=null;const r=grade(a);assert.equal(r.formScore.correct,49);assert.equal(r.caseScore.correct,19);assert.equal(r.caseScore.total,20);assert.deepEqual(r.incorrectIds,['T1.1']);});
test('wrong version, duplicate IDs, missing answers rejected; subset practice cannot alter source',()=>{let a=attempt();a.lesson.version=99;assert.throws(()=>grade(a));a=attempt();a.answers[0]={...a.answers[1]};assert.throws(()=>grade(a));a=attempt();a.answers.pop();assert.throws(()=>grade(a));a=attempt();const saved=JSON.stringify(a);const subset={...a,answers:a.answers.filter(q=>['T1.1','T4.3'].includes(q.id))};const r=G.evaluate(subset,key,lesson.cases,lesson.words,['T1.1','T4.3']);assert.equal(r.formScore.total,2);assert.equal(JSON.stringify(a),saved);});
